# Rules.mk

# Platform: GOKE HISI
TARGET_PLATFORM := NVIDIA

SDK_DIR:=$(shell pwd)
#SDK_DIR:=/home/skymixos/work/pro2_osc_prj

MONITOR_DIR=$(SDK_DIR)/init
LOGD_DIR=$(SDK_DIR)/logd
LOGCAT_DIR=$(SDK_DIR)/logcat
PROP_TOOLS=$(SDK_DIR)/prop_tools
EXTLIBS=$(SDK_DIR)/extlib

LIBCUTILS=$(EXTLIBS)/libcutils
LIBLOG=$(EXTLIBS)/liblog
LIBSYSUTILS=$(EXTLIBS)/libsysutils
LIBUTILS=$(EXTLIBS)/libutils
LIBEV=$(EXTLIBS)/libev-master

PRO2_SERVICE=$(SDK_DIR)/pro2_service
UPDATE_CHECK=$(SDK_DIR)/update_check
UPDATE_TOOL=$(SDK_DIR)/update_tool
UPDATE_APP=$(SDK_DIR)/update_app
VOLD_DIR=$(SDK_DIR)/vold

export SDK_DIR EXTLIBS MONITOR_DIR LOGD_DIR LOGCAT_DIR PROP_TOOLS LIBCUTILS LIBLOG LIBSYSUTILS LIBUTILS PRO2_SERVICE \
	UPDATE_CHECK UPDATE_APP VOLD_DIR

ifeq ("$(TARGET_PLATFORM)", "NVIDIA")
#TOOLCHAIN_DIR=/opt/install
CROSS_TOOLS=
#CROSS_TOOLS=aarch64-linux-gnu-
CC=$(CROSS_TOOLS)gcc
CPLUSPLUS=$(CROSS_TOOLS)g++
AR=$(CROSS_TOOLS)ar
STRIP=$(CROSS_TOOLS)strip
ARCH=aarch64-linux-gnu

else

CROSS_TOOL_DIR=$(DIDI_SDK_DIR)/cross_tools/goke_ct_glibc
CROSS_TOOLS=$(CROSS_TOOL_DIR)/4.6.1/usr/bin/arm-goke-linux-gnueabi-
CC=$(CROSS_TOOLS)gcc
CPLUSPLUS=$(CROSS_TOOLS)g++
AR=$(CROSS_TOOLS)ar
STRIP=$(CROSS_TOOLS)strip
endif

export TOOLCHAIN_DIR CC CPLUSPLUS AR STRIP ARCH


