Import('com_env')
#######################################################
# Compile for bootanimation
# Copyright Insta360 @ 2016 - 2025
#######################################################

import config

src = Glob('*.cpp')
src += [config.PRO2_SERVICE + '/fifo.cpp']
src += [config.PRO2_SERVICE + '/hw/oled_module.cpp']
src += [config.PRO2_SERVICE + '/hw/oled_light.cpp']
src += [config.PRO2_SERVICE + '/hw/battery_interface.cpp']
src += [config.PRO2_SERVICE + '/hw/ins_i2c.cpp']
src += [config.PRO2_SERVICE + '/hw/ins_gpio.cpp']
src += [config.PRO2_SERVICE + '/MenuUI.cpp']
src += [config.PRO2_SERVICE + '/InputManager.cpp']
src += [config.PRO2_SERVICE + '/NetManager.cpp']
src += [config.PRO2_SERVICE + '/pro_cfg.cpp']

src += [config.PRO2_SERVICE + '/util/arlog.c']
src += [config.PRO2_SERVICE + '/util/stlog.cpp']
src += [config.PRO2_SERVICE + '/util/md5.cpp']
src += [config.PRO2_SERVICE + '/util/ARMessage.cpp']
src += [config.PRO2_SERVICE + '/util/ARLooper.cpp']
src += [config.PRO2_SERVICE + '/util/update_oled.cpp']
src += [config.PRO2_SERVICE + '/util/update_util.cpp']
src += [config.PRO2_SERVICE + '/util/cJSON.c']
src += [config.PRO2_SERVICE + '/util/bytes_int_convert.cpp']
src += [config.PRO2_SERVICE + '/util/util.cpp']
src += [config.PRO2_SERVICE + '/util/pro_version.cpp']

src += [config.PRO2_SERVICE + '/NetlinkEvent.cpp']
src += [config.PRO2_SERVICE + '/NetlinkHandler.cpp']
src += [config.PRO2_SERVICE + '/NetlinkListener.cpp']
src += [config.PRO2_SERVICE + '/NetlinkManager.cpp']
src += [config.PRO2_SERVICE + '/SocketListener.cpp']
src += [config.PRO2_SERVICE + '/SocketClient.cpp']
src += [config.PRO2_SERVICE + '/VolumeManager.cpp']
src += [config.PRO2_SERVICE + '/Process.cpp']
src += [config.PRO2_SERVICE + '/forkUtil.cpp']



src += [config.LIBLOG + '/logd_write.c']
src += [config.LIBLOG + '/log_event_write.c']
src += [config.LIBLOG + '/logprint.c']
src += [config.LIBLOG + '/event_tag_map.c']
src += [config.LIBLOG + '/log_time.cpp']

src += [config.LIBCUTILS + '/system_properties.c']



#SOURCES += $(LIBCUTILS)/socket_local_server.c
#SOURCES += $(LIBCUTILS)/socket_local_client.c
#SOURCES += $(LIBCUTILS)/klog.c
#SOURCES += $(LIBCUTILS)/uevent.c
#SOURCES += $(LIBCUTILS)/system_properties.c


com_env['CXXFLAGS'] += ' -I' + config.PRO2_SERVICE + '/include'
#com_env['LIBS'] += ['rt']
#com_env['LIBS'] += ['pthread']
update_check_obj = com_env.Object(src)

Return('update_check_obj')

